name: flutter_gym_app
description: Gym app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+3
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.5
  fluttericon: ^1.0.7
  url_launcher: ^5.7.8
  qr_flutter: ^3.2.0
  qrscan: ^0.2.17
  flutter_statusbarcolor: ^0.2.3
  rflutter_alert: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  sqflite: ^1.3.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_icons:
  image_path: 'assets/gymLogo.png'
  android: true
  ios: true