name: flutter_gym_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  devicelocale: ^0.3.1
  http: ^0.12.2
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2
  rflutter_alert: ^1.0.3
  qr_flutter: ^3.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
  uses-material-design: true
